package approval

import (
	"context"
	"errors"
	"time"

	"github.com/imbrooklyn/kupilot/internal/domain"
)

var (
	ErrInvalidRestartDeploymentExecution = errors.New("restart Deployment execution data is invalid")
	ErrPreWritePersistenceUnavailable    = errors.New("pre-write approval persistence is unavailable")
)

// RestartDeploymentObservation is the safe result of the mandatory fresh
// Deployment read. ResourceVersion is observation metadata, never proposal or
// model input, and is admitted only as the subsequent concurrency precondition.
type RestartDeploymentObservation struct {
	Scope                domain.ScopeSnapshot
	DeploymentName       string
	DeploymentUID        string
	TemplateFingerprint  string
	DeploymentGeneration int64
	ResourceVersion      string
}

// Validate checks the complete fresh target projection without vendor values.
func (observation RestartDeploymentObservation) Validate() error {
	reference := domain.ResourceRef{
		APIVersion:      domain.RestartDeploymentTargetAPIVersion,
		Kind:            domain.RestartDeploymentTargetKind,
		Namespace:       observation.Scope.Namespace,
		Name:            observation.DeploymentName,
		UID:             observation.DeploymentUID,
		ResourceVersion: observation.ResourceVersion,
	}
	if observation.Scope.Validate() != nil || !domain.ValidContextName(observation.Scope.Context) ||
		!domain.ValidNamespaceName(observation.Scope.Namespace) || observation.Scope.Generation < 1 ||
		reference.Validate() != nil ||
		!domain.ApprovalDigest(observation.TemplateFingerprint).Valid() || observation.DeploymentGeneration < 1 {
		return ErrInvalidRestartDeploymentExecution
	}
	return nil
}

// RestartDeploymentExecution is created only after deterministic revalidation.
// It contains no caller-selected patch, YAML, annotation, value, or time.
type RestartDeploymentExecution struct {
	observation RestartDeploymentObservation
}

// NewRestartDeploymentExecution binds a fresh observation to the approved
// canonical intent while deliberately ignoring proposal-time resource version.
func NewRestartDeploymentExecution(
	intent domain.OperationIntent,
	observation RestartDeploymentObservation,
) (RestartDeploymentExecution, error) {
	if intent.Validate() != nil || observation.Validate() != nil ||
		intent.Scope != observation.Scope || intent.DeploymentName != observation.DeploymentName ||
		intent.DeploymentUID != observation.DeploymentUID ||
		intent.TemplateFingerprint != observation.TemplateFingerprint ||
		intent.DeploymentGeneration != observation.DeploymentGeneration ||
		intent.PolicyVersion != domain.RestartDeploymentApprovalPolicyVersion {
		return RestartDeploymentExecution{}, ErrInvalidRestartDeploymentExecution
	}
	return RestartDeploymentExecution{observation: observation}, nil
}

// Validate checks that the sealed execution still contains one exact target.
func (execution RestartDeploymentExecution) Validate() error {
	return execution.observation.Validate()
}

// Observation returns a value copy of the fresh target projection for the
// fixed Kubernetes adapter. Callers cannot replace the sealed projection.
func (execution RestartDeploymentExecution) Observation() RestartDeploymentObservation {
	return execution.observation
}

// RestartDeploymentResult is the bounded successful PATCH response projection.
// RestartedAt is generated by the Kubernetes adapter and is never an input.
type RestartDeploymentResult struct {
	Scope                   domain.ScopeSnapshot
	DeploymentName          string
	DeploymentUID           string
	PreviousResourceVersion string
	ResourceVersion         string
	RestartedAt             time.Time
}

// Validate checks only safe target, concurrency, and UTC result metadata.
func (result RestartDeploymentResult) Validate() error {
	previous := domain.ResourceRef{
		APIVersion: domain.RestartDeploymentTargetAPIVersion, Kind: domain.RestartDeploymentTargetKind,
		Namespace: result.Scope.Namespace, Name: result.DeploymentName, UID: result.DeploymentUID,
		ResourceVersion: result.PreviousResourceVersion,
	}
	current := previous
	current.ResourceVersion = result.ResourceVersion
	if result.Scope.Validate() != nil || !domain.ValidContextName(result.Scope.Context) ||
		!domain.ValidNamespaceName(result.Scope.Namespace) || result.Scope.Generation < 1 ||
		previous.Validate() != nil || current.Validate() != nil || result.RestartedAt.IsZero() ||
		result.RestartedAt.Location() != time.UTC || result.RestartedAt.UnixMilli() < 0 ||
		!result.RestartedAt.Equal(time.UnixMilli(result.RestartedAt.UnixMilli()).UTC()) {
		return ErrInvalidRestartDeploymentExecution
	}
	return nil
}

// RestartDeploymentRevalidator owns the one exact fresh Deployment read.
type RestartDeploymentRevalidator interface {
	RevalidateApprovedRestart(context.Context, domain.OperationIntent) (RestartDeploymentObservation, error)
}

// RestartDeploymentExecutor is the sole fixed write seam. Only Service calls
// it, after durable pre-write intent and audit have committed.
type RestartDeploymentExecutor interface {
	ExecuteApprovedRestart(context.Context, RestartDeploymentExecution) (RestartDeploymentResult, error)
}

// PreWriteStore owns the two exact durable checks around fresh revalidation.
// ConsumeWithAudit is one short transaction and never spans Kubernetes I/O.
type PreWriteStore interface {
	VerifyApproved(context.Context, StoredRequest, StoredDecision) error
	ConsumeWithAudit(context.Context, StoredRequest, StoredDecision, StoredRequest, domain.AuditEvent) error
}

// CurrentScope supplies the complete currently verified ClusterScope.
type CurrentScope interface {
	CurrentScope() (domain.ClusterScope, bool)
}

// AuditIdentifierSource supplies application-generated durable AuditEvent IDs.
type AuditIdentifierSource interface {
	NewAuditEventID() (domain.AuditEventID, error)
}

func writeIntentAudit(id domain.AuditEventID, request StoredRequest) (domain.AuditEvent, error) {
	if !id.Valid() || request.Validate() != nil || request.State != domain.ApprovalStateConsumed {
		return domain.AuditEvent{}, ErrInvalidStoredApproval
	}
	operation := string(request.Intent.Operation)
	detail := string(domain.ApprovalReasonConsumed)
	policy := request.Intent.PolicyVersion
	scope := request.Intent.Scope
	sessionID, runID := request.SessionID, request.RunID
	subject := domain.ResourceRef{
		APIVersion: domain.RestartDeploymentTargetAPIVersion,
		Kind:       domain.RestartDeploymentTargetKind,
		Namespace:  request.Intent.Scope.Namespace,
		Name:       request.Intent.DeploymentName,
		UID:        request.Intent.DeploymentUID,
	}
	event := domain.AuditEvent{
		ID: id, SessionID: &sessionID, RunID: &runID,
		Type: domain.AuditEventWriteIntent, Actor: domain.AuditActorSystem, Outcome: domain.AuditOutcomeSuccess,
		Scope: &scope, Subject: &subject,
		Details: domain.AuditDetails{
			Operation: &operation, DetailCode: &detail, PolicyVersion: &policy,
		},
		CorrelationID: string(request.ID), IntegrityHash: string(request.Digest),
		OccurredAt: request.StateChangedAt,
	}
	if request.ValidateAudit(event) != nil {
		return domain.AuditEvent{}, ErrInvalidStoredApproval
	}
	return event, nil
}
